
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/travel360
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

info:
  app:
    name: @project.name@
    version: @project.version@
    profile: ${spring.profiles.active}
  serverInfo:
    os: ${os.name}
  user:
    timeZone: ${user.timezone}
    country: ${user.country}
  metrics:


management:
  endpoints:
    web:
      exposure:
        include: '*'